# Generated by Django 4.1.3 on 2022-11-06 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
