# Generated by Django 4.1.3 on 2022-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="blog title"
            ),
        ),
    ]
