# Generated by Django 4.1.3 on 2022-11-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_subscription_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
