# Generated by Django 4.1.3 on 2022-11-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_subscription_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-published_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-title"]},
        ),
    ]
