# Generated by Django 4.1.3 on 2022-11-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_user_full_name_user_sync_ongoing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default="sample-slug"),
            preserve_default=False,
        ),
    ]
